//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terazi_Dunyasi_Project_v12
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adresler()
        {
            this.Siparislers = new HashSet<Siparisler>();
        }
    
        public int AdresID { get; set; }
        public int UyeID { get; set; }
        public string AdresBaslik { get; set; }
        public string Adres { get; set; }
        public string Ilce { get; set; }
        public string Sehir { get; set; }
        public string Ulke { get; set; }
    
        public virtual Uyeler Uyeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparislers { get; set; }
    }
}
